version: "3.8"

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: oil_user
      POSTGRES_PASSWORD: oilbenzin
      POSTGRES_DB: petrol_db
    ports:
      - "5432:5432"